@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.food.ordering.system.order.service.dataaccess.order.entity.OrderAddressEntity",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_3148894 { 
   	label=food
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1207113060 { 
   	label=ordering
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   OrderAddressEntity900050846[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderAddressEntity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   city: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   order: OrderEntity [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   postalCode: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   street: String [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ builder(): OrderAddressEntityBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OrderEntity900050846[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderEntity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   address: OrderAddressEntity [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   customerId: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   failureMessages: String [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   id: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   items: List&lt;OrderItemEntity&gt; [0..*]</TD></TR>
<TR><TD ALIGN="LEFT" >-   orderStatus: OrderStatus [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   price: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   restaurantId: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   trackingId: UUID [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ builder(): OrderEntityBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OrderItemEntity900050846[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderItemEntity</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   order: OrderEntity [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   price: BigDecimal [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   productId: UUID [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   quantity: Integer [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   subTotal: BigDecimal [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ builder(): OrderItemEntityBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

OrderItemEntityId900050846[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)OrderItemEntityId</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   id: Long [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   order: OrderEntity [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ builder(): OrderItemEntityIdBuilder</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
OrderAddressEntity900050846 -> OrderEntity900050846[label="order
[0..1]"];
OrderEntity900050846 -> OrderAddressEntity900050846[label="address
[0..1]"];
OrderEntity900050846 -> OrderItemEntity900050846[label="items
[0..*]"];
OrderItemEntity900050846 -> OrderEntity900050846[label="order
[0..1]"];
OrderItemEntityId900050846 -> OrderEntity900050846[label="order
[0..1]"];
    
}
@enduml